#!/bin/sh

commit_msg_file=$1

if ! npx --no -- commitlint --edit "$commit_msg_file"; then
  echo ""
  echo "❌ Commit inválido."
  echo "✅ Formato correcto: prefijo(contexto-modulo): descripción breve"
  echo ""
  exit 1
fi

exit 0
